### ISSUE TITLE
Device->Devices, EndpointApp -> EndpointApps

### ISSUE THREAD

**Issue by elear** [iot-onboarding/scim-devices#26]
Pluralize as requested by Pamela Dingle, to maintain model consistency

**Comment by rohitmohan96** [comment]
RFC 7643 defines the resource as `User` and the schema uri is `urn:ietf:params:scim:schemas:core:2.0:User`. 
Similarly, it is `Group` and `urn:ietf:params:scim:schemas:core:2.0:Group`. 

This is why we have the `Device` and `EndpointApp` resources as singular.
