### ISSUE TITLE
Corrections related to EndpointApps

### ISSUE THREAD

**Issue by rohitmohan96** [iot-onboarding/scim-devices#35]
1. The `value` attribute here needs to be readWrite and not readOnly since this can be provided as part of the SCIM request. 
https://github.com/iot-onboarding/scim-devices/blob/39c0b0280e89bc9279a868a0e43c2bccfd30cca9/draft-ietf-scim-device-model.mkd?plain=1#L871-L875 https://github.com/iot-onboarding/scim-devices/blob/39c0b0280e89bc9279a868a0e43c2bccfd30cca9/draft-ietf-scim-device-model.mkd?plain=1#L891
2. The `telemetryEnterpriseEndpoint` example has a `https://` URL. Maybe this should be `mqtts://` instead?
https://github.com/iot-onboarding/scim-devices/blob/39c0b0280e89bc9279a868a0e43c2bccfd30cca9/examples/SCIM_device_endpoints_with_ble_object.json#L44-L45
    - The draft on the datatracker is also missing a colon in the URLs but looks like that is fixed here already. 
    - Nit: Not sure if we want a car rental website as the domain for the enterprise endpoint? The document uses `example.com` everywhere else in the document.

**Comment by elear** [comment]
You must discuss this on the mailing list.
