### ISSUE TITLE
Reference to obsolete subjectAlternateName

### ISSUE THREAD

**Issue by rohitmohan96** [iot-onboarding/scim-devices#40]
The subject alternate name field was removed in the endpoint app schema so this line is no longer valid. 

https://github.com/iot-onboarding/scim-devices/blob/8dc4707fd2f670814fb6658080659d9b7faed649/draft-ietf-scim-device-model.mkd?plain=1#L383C13-L386C65

**Comment by elear** [comment]
I am still not sure this text is wrong, because there is clear guidance as to which SAN is valid (eg, dnsNames).  What isn't clear is whether the TLS implementation must validate the peer by doing an inverse lookup.  Please bring this forward to the mailing list for discussion.

**Comment by elear** [comment]
Key issue: if a SAN **is** used in the client cert, then servers must confirm that the peer name is being used in the TCP connection.
