### ISSUE TITLE
Enterprise endpoint fields must be optional

### ISSUE THREAD

**Issue by rohitmohan96** [iot-onboarding/scim-devices#41]
In section 7.6.1, `deviceControlEnterpriseEndpoint` and `telemetryEnterpriseEndpoint` are marked as required.
I believe there are some cases where these fields wouldn't exist and should be optional. 

For example, it is possible that telemetry isn't supported and only control app functionality is provided by the gateway. In this case, there wouldn't be an appropriate `telemetryEnterpriseEndpoint` to be returned by the scim server.

**Comment by elear** [comment]
I think I agree.  However, there's a catch.  The client implementation needs to know the answer to these questions, and must introspect for the schema extension before transacting; and it is important to NOT try to control a device in an environment that can't support it.  So for this one, please bring to the list and create a proposed PR.
